#! /bin/bash
DIR=$1  # the dir with the query mplans and the metadata files
shift

OUT=/tmp/vdlresults/$(basename $DIR)

rm -rf $OUT
mkdir -p $OUT

COUNT=0
SUCCESS=0
for test in $(ls $DIR/*plan)
do
    COUNT=$((COUNT+1))
    FILE=$(basename $test)
    #set -x
    COMMAND="./mplan2vdl -b $DIR/bounds.csv -s $DIR/schema.msqldump $@ $test 1>/$OUT/$FILE.vdl 2>/$OUT/$FILE.err"
    #echo $COMMAND
    eval $COMMAND
    EXIT_STATUS=$?
    #set +x
    if [[ $EXIT_STATUS == 0 ]]
    then
        SUCCESS=$((SUCCESS+1))
        D=$(wc -l $OUT/$FILE.vdl | awk '{print $1}')
       echo "$FILE: success. vdl at $OUT/$FILE.vdl $D voodoo statements"
    else
       echo "$FILE: FAILURE. log at $OUT/$FILE.err"
       rm $OUT/$FILE.vdl
    fi
done

echo "SUCCESS/TOTAL = $SUCCESS/$COUNT"
